# Generated by Django 3.0.8 on 2020-07-05 23:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('timeStamp', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('education_qualification', models.TextField()),
                ('experiences', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tech_stack', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
