# Generated by Django 3.0.8 on 2020-07-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Profiles',
        ),
    ]
