# Generated by Django 3.0.8 on 2020-07-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Portfolio', 'Name', 'name'),
        migrations.RenameField('Portfolio', 'Education_Qualification', 'experiences'),
        migrations.RenameField('Portfolio', 'Experiences', 'education_qualification'),
        migrations.RenameField('Portfolio', 'TechStack', 'tech_stack'),
    ]
